### ISSUE TITLE
 <4442> Gothik the Harvester(25)
New timer: P2 teleport timer - Start 20 sec timer "Teleport" when p2 begins(on repeat). stop this timer when boss reaches 30% hp (gates open)

### ISSUE THREAD

**Issue by a1dancole** [SiarkowyForks/dbm-wotlk5man-lfr#14]
<4442> Gothik the Harvester(25)
New timer: P2 teleport timer - Start 20 sec timer "Teleport" when p2 begins(on repeat). stop this timer when boss reaches 30% hp (gates open)  - raised by Holycoke via Discord link: https://discord.com/channels/808813760978223135/882719072763121685/883385115017900032

**Comment by Holycoke** [comment]
do you require an event from combat log to do this one?

**Comment by Siarkowy** [comment]
Any of (1) combat log event, (2) boss yell or (3) emote would be needed to mark Phase 2 Enter.

Checking for 30% hp is trickier; if there's none of above markers, DBM would need to constantly sync boss health a la Kalecgos health bars - and then decide we hit 30%.

**Comment by Holycoke** [comment]
[https://cdn.discordapp.com/attachments/449076117186543616/884144984297709659/unknown.png](url)
