### ISSUE TITLE
 <4442> Sapphiron(25) 
New timer "Frozen Orbs" 
On pull 30 second timer (1 time use)
after each landing 30 second timer, followed by a 25 sec timer 

when "Air phase" timer starts, start a 30 sec timer, followed by a 25 sec timer. but first ground phase is shorter, and only 1 wave of orbs come, all other ground phases have 30 sec + 25 sec timers

### ISSUE THREAD

**Issue by a1dancole** [SiarkowyForks/dbm-wotlk5man-lfr#29]
<4442> Sapphiron(25) 
New timer "Frozen Orbs" 
On pull 30 second timer (1 time use)
after each landing 30 second timer, followed by a 25 sec timer 

when "Air phase" timer starts, start a 30 sec timer, followed by a 25 sec timer. but first ground phase is shorter, and only 1 wave of orbs come, all other ground phases have 30 sec + 25 sec timers  - raised by Holycoke via Discord link: https://discord.com/channels/808813760978223135/882719072763121685/884044386067972126

**Comment by Siarkowy** [comment]
Is this in fact 2 issues in one?

**Comment by Holycoke** [comment]
All frozen orb timers. maybe a bit poorly worded...

fight goes like this:

Pull
30 sec
frozen orbs
18 sec ish?
air phase
landing
30 sec 
frozen orbs
25 sec
frozen orbs
air phase
landing 
30 sec
frozen orbs
25 sec
frozen orbs
air phase
landing 

repeat
