### ISSUE TITLE
Make it unzip the sub folders instead of main folder?

### ISSUE THREAD

**Issue by a1dancole** [SiarkowyForks/dbm-wotlk5man-lfr#3]
4442 - Make it unzip the sub folders instead of main folder?  - raised by Holycoke via Discord link: https://discord.com/channels/808813760978223135/882719072763121685/882750343358857307

**Comment by Siarkowy** [comment]
This could be implemented as GitHub release action on any merge to master branch.

However, at the same time, DBM revision needs to be bumped to distinguish installed add-on version with:

    /dbm ver2
