### ISSUE TITLE
 <4445> Noth the Plaguebringer(25) 

New warning , no idea what to call it... 

triggered by Paralyze debuff

### ISSUE THREAD

**Issue by a1dancole** [SiarkowyForks/dbm-wotlk5man-lfr#36]
<4445> Noth the Plaguebringer(25) 

New warning , no idea what to call it... 

triggered by Paralyze debuff  - raised by Holycoke via Discord link: https://discord.com/channels/808813760978223135/882719072763121685/884778895742742558

**Comment by Holycoke** [comment]
Paralyze spell ID - 38132

https://wotlkdb.com/?spell=38132

**Comment by Holycoke** [comment]
Name could be - Enraged Skeleton
